// Solar system configuration

export const config = {
  sun: {
    name: "Sun",
    radius: 10,
    color: [1.0, 0.9, 0.2],
    texture: "textures/sun_2k.jpg",
    position: [0, 0, 0],
    rotationSpeed: 0.04,
    axialTilt: 7.25,
    emissive: true,
  },
  planets: [
    {
      name: "Mercury",
      radius: 0.35,
      color: [0.7, 0.7, 0.7],
      texture: "textures/mercury_2k.jpg",
      orbitRadius: 15,
      orbitSpeed: 4.15,
      rotationSpeed: 0.017,
      startAngle: 0,
      eccentricity: 0.206,
      axialTilt: 0.034,
      inclination: 7.0,
    },
    {
      name: "Venus",
      radius: 0.87,
      color: [0.9, 0.7, 0.5],
      texture: "textures/venus_2k.jpg",
      orbitRadius: 27.7,
      orbitSpeed: 1.62,
      rotationSpeed: -0.004,
      startAngle: 120,
      axialTilt: 177.4,
      inclination: 3.39,
    },
    {
      name: "Earth",
      radius: 0.91,
      color: [0.2, 0.5, 0.9],
      texture: "textures/earth_2k.jpg",
      orbitRadius: 38.5,
      orbitSpeed: 1.0,
      rotationSpeed: 1.0,
      startAngle: 240,
      axialTilt: 23.44,
      inclination: 0.0,
      moons: [
        {
          name: "Moon",
          radius: 0.25,
          color: [0.8, 0.8, 0.8],
          texture: "textures/moon_2k.jpg",
          orbitRadius: 2.5,
          orbitSpeed: 13.4,
          orbitalTilt: 5.14,
        },
      ],
    },
    {
      name: "Mars",
      radius: 0.49,
      color: [0.85, 0.35, 0.2],
      texture: "textures/mars_2k.jpg",
      orbitRadius: 58.5,
      orbitSpeed: 0.53,
      rotationSpeed: 0.97,
      startAngle: 45,
      eccentricity: 0.093,
      axialTilt: 25.19,
      inclination: 1.85,
      emissive: false,
      moons: [
        {
          name: "Phobos",
          radius: 0.08,
          color: [0.6, 0.6, 0.6],
          orbitRadius: 1.4,
          orbitSpeed: 1148,
        },
        {
          name: "Deimos",
          radius: 0.05,
          color: [0.65, 0.65, 0.65],
          orbitRadius: 3.4,
          orbitSpeed: 290,
        },
      ],
    },
    {
      name: "Jupiter",
      radius: 10.2,
      color: [0.8, 0.7, 0.6],
      texture: "textures/jupiter_2k.jpg",
      orbitRadius: 200,
      orbitSpeed: 0.084,
      rotationSpeed: 2.4,
      startAngle: 180,
      axialTilt: 3.13,
      inclination: 1.31,
      moons: [
        {
          name: "Io",
          radius: 0.35,
          color: [0.9, 0.8, 0.3],
          orbitRadius: 14,
          orbitSpeed: 565,
        },
        {
          name: "Europa",
          radius: 0.3,
          color: [0.9, 0.95, 1.0],
          orbitRadius: 22,
          orbitSpeed: 282,
        },
        {
          name: "Ganymede",
          radius: 0.5,
          color: [0.7, 0.7, 0.7],
          orbitRadius: 35,
          orbitSpeed: 140,
        },
        {
          name: "Callisto",
          radius: 0.45,
          color: [0.5, 0.5, 0.5],
          orbitRadius: 62,
          orbitSpeed: 60,
        },
      ],
    },
    {
      name: "Saturn",
      radius: 8.6,
      color: [0.9, 0.8, 0.6],
      texture: "textures/saturn_2k.jpg",
      orbitRadius: 367,
      orbitSpeed: 0.034,
      rotationSpeed: 2.2,
      startAngle: 300,
      hasRings: true,
      rings: [
        { inner: 10.578, outer: 13.072, color: [0.7, 0.65, 0.55] },
        { inner: 13.072, outer: 16.77, color: [0.85, 0.75, 0.6] },
        { inner: 17.372, outer: 19.522, color: [0.8, 0.7, 0.55] },
      ],
      axialTilt: 26.73,
      inclination: 2.49,
      moons: [
        {
          name: "Mimas",
          radius: 0.2,
          color: [0.75, 0.75, 0.75],
          orbitRadius: 20.5,
          orbitSpeed: 1063,
        },
        {
          name: "Enceladus",
          radius: 0.25,
          color: [0.95, 0.95, 0.95],
          orbitRadius: 23,
          orbitSpeed: 730,
        },
        {
          name: "Tethys",
          radius: 0.3,
          color: [0.85, 0.85, 0.85],
          orbitRadius: 26,
          orbitSpeed: 529,
        },
        {
          name: "Dione",
          radius: 0.35,
          color: [0.8, 0.8, 0.8],
          orbitRadius: 30,
          orbitSpeed: 365,
        },
        {
          name: "Rhea",
          radius: 0.5,
          color: [0.7, 0.7, 0.7],
          orbitRadius: 35,
          orbitSpeed: 221,
        },
        {
          name: "Titan",
          radius: 0.9,
          color: [0.9, 0.7, 0.5],
          orbitRadius: 40,
          orbitSpeed: 63,
        },
        {
          name: "Iapetus",
          radius: 0.5,
          color: [0.6, 0.6, 0.6],
          orbitRadius: 60,
          orbitSpeed: 13,
        },
      ],
    },
    {
      name: "Uranus",
      radius: 3.65,
      color: [0.5, 0.8, 0.9],
      texture: "textures/uranus_2k.jpg",
      orbitRadius: 738,
      orbitSpeed: 0.012,
      rotationSpeed: 1.4,
      startAngle: 90,
      axialTilt: 97.77,
      inclination: 0.77,
      moons: [
        {
          name: "Miranda",
          radius: 0.15,
          color: [0.7, 0.7, 0.7],
          orbitRadius: 8,
          orbitSpeed: 805,
        },
        {
          name: "Ariel",
          radius: 0.35,
          color: [0.85, 0.85, 0.85],
          orbitRadius: 12,
          orbitSpeed: 371,
        },
        {
          name: "Umbriel",
          radius: 0.35,
          color: [0.4, 0.4, 0.4],
          orbitRadius: 17,
          orbitSpeed: 242,
        },
        {
          name: "Titania",
          radius: 0.48,
          color: [0.75, 0.75, 0.75],
          orbitRadius: 27,
          orbitSpeed: 115,
        },
        {
          name: "Oberon",
          radius: 0.46,
          color: [0.65, 0.65, 0.65],
          orbitRadius: 37,
          orbitSpeed: 81,
        },
      ],
    },
    {
      name: "Neptune",
      radius: 3.53,
      color: [0.3, 0.4, 0.9],
      texture: "textures/neptune_2k.jpg",
      orbitRadius: 1156,
      orbitSpeed: 0.006,
      rotationSpeed: 1.5,
      startAngle: 210,
      axialTilt: 28.32,
      inclination: 1.77,
      moons: [
        {
          name: "Triton",
          radius: 0.55,
          color: [0.8, 0.85, 0.9],
          orbitRadius: 15,
          orbitSpeed: -60, // Negative for retrograde orbit
        },
        {
          name: "Proteus",
          radius: 0.2,
          color: [0.5, 0.5, 0.5],
          orbitRadius: 5,
          orbitSpeed: 200,
        },
        {
          name: "Nereid",
          radius: 0.12,
          color: [0.6, 0.6, 0.6],
          orbitRadius: 25,
          orbitSpeed: 8,
        },
      ],
    },
  ],
  asteroidBelt: {
    count: 800,
    innerRadius: 100,
    outerRadius: 150,
    thickness: 8,
    orbitSpeed: 0.2,
    color: [0.6, 0.5, 0.4],
  },
  kuiperBelt: {
    count: 1200,
    innerRadius: 1200,
    outerRadius: 1600,
    thickness: 50,
    orbitSpeed: 0.003,
    color: [0.7, 0.8, 0.9],
  },
};
